routes:
# =========================
# Health Check Microservice
# =========================

  - regex: '^/health(/*[a-zA-Z0-9]*)?'
    inputModel: main.daos.Healthcheck
    outputModel: main.daos.Healthcheck
    controller: main.controllers.HealthcheckController

  - regex: '^/dbhealth(/*[a-zA-Z0-9]*)?'
    inputModel: main.daos.Healthcheck
    outputModel: main.daos.Healthcheck
    controller: main.controllers.DatabaseHealthcheckController

# =========================
# Challenge Microservice
# =========================

  - regex: '^/challenge(/*[a-zA-Z0-9]*)?'
    inputModel: main.daos.Challenge
    outputModel: main.daos.Challenge
    controller: main.controllers.ChallengeController

# =========================
# Challenges Microservice
# =========================

  - regex: '^/challenges(/*[a-zA-Z0-9]*)?'
    inputModel: main.daos.Challenge
    outputModel: main.daos.Challenge
    controller: main.controllers.ChallengeController

# =========================
# Balances Microservice
# =========================

  - regex: '^/challenges/balances(/*[a-zA-Z0-9]*)?'
    inputModel: main.daos.Challenge
    outputModel: main.daos.Challenge
    controller: main.controllers.ChallengeController

# =========================
# Token Microservice
# =========================

#  - regex: '^/token(/*[a-zA-Z0-9]*)?'
#    inputModel: main.daos.Token
#    outputModel: main.daos.Token
#    controller: main.controllers.TokenController
#
#  - regex: '^/tokens(/*[a-zA-Z0-9]*)?'
#    inputModel: main.daos.Token
#    outputModel: main.daos.Token
#    controller: main.controllers.TokensController

# =========================
# Transactions Microservice
# =========================
#
#  - regex: '^/transaction(/*[a-zA-Z0-9]*)?'
#    inputModel: main.daos.Transaction
#    outputModel: main.daos.Transaction
#    controller: main.controllers.TransactionController

